apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: m1000e
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: m1000e-prometheus

